// Generated by CoffeeScript 1.6.2
(function() {
  define(["jquery", "backbone"], function($, backbone) {
    App.Models.tuktuk = backbone.Model.extend();
    App.Collections.tuktuk = backbone.Collection.extend();
    return App.Views.tuktuk = backbone.View.extend({
      el: "body",
      initialize: function() {},
      render: function() {}
    });
  });

}).call(this);
