// Generated by CoffeeScript 1.6.2
(function() {
  define(["underscore"], function(_) {
    var getInternetExplorerVersion;

    App.Config = _.extend(App.Config, {
      router: {
        pushState: true
      },
      dataPaths: {},
      keys: {}
    });
    App.Config = _.extend(App.Config, {
      extPaths: {}
    });
    require.config({
      paths: {
        text: "plugins/require/text",
        order: "plugins/require/order",
        async: "plugins/require/async",
        depend: "plugins/require/depend",
        json: "plugins/require/json",
        addThis: "addThis",
        google_analytics: "google_analytics",
        templates: "templates"
      }
    });
    getInternetExplorerVersion = function() {
      var re, rv, ua;

      rv = -1;
      if (navigator.appName === "Microsoft Internet Explorer") {
        ua = navigator.userAgent;
        re = new RegExp("MSIE ([0-9]{1,}[.0-9]{0,})");
        if (re.exec(ua) != null) {
          rv = parseFloat(RegExp.$1);
        }
      }
      return rv;
    };
    if (getInternetExplorerVersion() > -1 && getInternetExplorerVersion() < 9) {
      return require.config({
        paths: {
          jquery: "plugins/jquery/fallback_jquery_ie8/jquery.min"
        }
      });
    }
  });

}).call(this);
