// Generated by CoffeeScript 1.6.2
(function() {
  describe("Namespace", function() {
    it("provides the 'App' object", function() {
      expect(window.App).to.be.an("object");
      return expect(App).to.include.keys("Config", "Collections", "Models", "Routers", "Templates", "Views");
    });
    return it("provide the 'app' object", function() {
      return expect(app).to.be.an("object");
    });
  });

}).call(this);
