// Generated by CoffeeScript 1.6.2
(function() {
  define(["jam/chai/chai.js", "plugins/sinon/sinon-chai.js", "jam/sinon/sinon.js"], function(chai, sinonChai, sinon) {
    window.should = chai.should();
    window.expect = chai.expect;
    require.config({
      catchError: true,
      baseUrl: "../../js/",
      paths: {
        text: "plugins/require/text",
        order: "plugins/require/order",
        async: "plugins/require/async",
        depend: "plugins/require/depend",
        json: "plugins/require/json",
        chai: "jam/chai/chai.js",
        sinonChai: "plugins/sinon/sinon-chai.js",
        sinon: "jam/sinon/sinon.js"
      }
    });
    return require(["json!../unit-test/test/config.json"], function(config) {
      var done, filesDone;

      require([config.main]);
      filesDone = [];
      done = function(name) {
        filesDone.push(name);
        if (filesDone.length === config.toTest.length) {
          return mocha.run();
        }
      };
      return require.onResourceLoad = function(context, map, depArray) {
        if (config.toTest.indexOf(map.name) > -1) {
          return require(["../unit-test/test/" + map.name + config.ext], function() {
            return done(map.name);
          });
        }
      };
    });
  });

}).call(this);
