// Generated by CoffeeScript 1.6.2
(function() {
  define(["jquery", "backbone", "underscore", "app/router", "app/modules/main", "app/modules/tuktuk"], function($, Backbone, _) {
    var initialize;

    return initialize = function() {
      app.main = new App.Views.main();
      app.tutuk = new App.Views.tuktuk({
        collection: new App.Collections.tuktuk({
          model: new App.Models.tuktuk()
        })
      });
      app.Router = new App.Routers.main({
        main: app.main,
        tuktuk: app.tutuk
      });
      return Backbone.history.start(App.Config.router);
    };
  });

}).call(this);
