// Generated by CoffeeScript 1.6.2
(function() {
  var _gaq;

  _gaq = [["_setAccount", window.App.keys.gAnalytics], ["_trackPageview"]];

  (function(d, t) {
    var g, s;

    g = d.createElement(t);
    s = d.getElementsByTagName(t)[0];
    g.async = 1;
    g.src = ("https:" === location.protocol ? "//ssl" : "//www") + ".google-analytics.com/ga.js";
    return s.parentNode.insertBefore(g, s);
  })(document, "script");

}).call(this);
