// Generated by CoffeeScript 1.6.2
(function() {
  define(["jquery", "backbone"], function($, Backbone) {
    return App.Routers.main = Backbone.Router.extend({
      initialize: function(opts) {},
      routes: {
        "*actions": "defaultAction"
      },
      defaultAction: function() {
        return true;
      }
    });
  });

}).call(this);
