// Generated by CoffeeScript 1.6.2
(function() {
  describe("Router", function() {
    var opts;

    opts = {
      trigger: true,
      replace: true
    };
    before(function() {
      this.sandbox = sinon.sandbox.create();
      this.sandbox.mock(App.Views.Main);
      this.sandbox.stub(App.Views.main.prototype);
      return App.Views.main.prototype.render.returns({
        $el: null
      });
    });
    it("expect a model class", function() {
      expect(App.Models.tuktuk).to.be.a("function");
      return expect(this.model).to.be.an("object");
    });
    it("expect a collection class", function() {
      expect(App.Collections.tuktuk).to.be.a("function");
      return expect(this.collection).to.be.an("object");
    });
    return it("expect a view class", function() {
      expect(App.Views.tuktuk).to.be.a("function");
      return expect(this.view).to.be.an("object");
    });
  });

}).call(this);
