// Generated by CoffeeScript 1.6.2
(function() {
  describe("Main module", function() {
    before(function() {
      return this.view = new App.Views.main();
    });
    after(function() {
      return this.view.remove();
    });
    return it("Class", function() {
      expect(App.Views.main).to.be.an("function");
      return expect(this.view).to.be.an("object");
    });
  });

}).call(this);
