// Generated by CoffeeScript 1.6.2
(function() {
  describe("Tuktuk module", function() {
    before(function() {
      this.model = new App.Models.tuktuk();
      this.collection = new App.Collections.tuktuk();
      return this.view = new App.Views.tuktuk();
    });
    after(function() {
      this.model.destroy();
      this.collection.remove();
      return this.view.remove();
    });
    it("expect a model class", function() {
      expect(App.Models.tuktuk).to.be.a("function");
      return expect(this.model).to.be.an("object");
    });
    it("expect a collection class", function() {
      expect(App.Collections.tuktuk).to.be.a("function");
      return expect(this.collection).to.be.an("object");
    });
    return it("expect a view class", function() {
      expect(App.Views.tuktuk).to.be.a("function");
      return expect(this.view).to.be.an("object");
    });
  });

}).call(this);
